dist: bionic

language: python

python: 3.7

cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - master
    - /^\d.\d+$/

install: pip install -r requirements.txt

script: make SPHINXOPTS=-nW html

notifications:
  email: false
  slack:
    rooms:
      - secure: "lgpsM4+irpCc7uO5nTU/uZMe2BaZVFeYWC1FwnbpVdNmuJWNDEQZSJtRX6wBk1pBw9Jdn9Dd0odEN2CUXRyB5hSq0UY7oWrtwY1uPIYxiaxnqOQ7E37OSgFwBBKJZP1/ACe1/Tm5rFthMo38OY14cG1wqYIdxCCT5BnxNSE0YM0vkaP55D2fdETe2yPMmaMw90tKFrmhJgflkGFt6WDrFgA8r3CcM4dkD3H8vkTpQMjNbTMORONfG3mthogImFCOCGwFvGbZFZOMwV0WFBJhxJWLTkcGSC+MWb+dnXVyzqUxT1hte/NAelysyxz4JBll5BwVAi62zaWcJiKO3YUViMA922y6hNgpd2qC2faDcAOYpidO+Tsayic3ji3ZACLlwKi3XitWlhYCWanh7MtMEE+JVjmvJbD5UeAMK0/+aAu23iy3X4cw6RV9mQqpGIWtKpJ3kZTy2MPrXYQaSMCJJjt3x31qsTtmjtFbZ2KjkQqs6gDtjURhsNne/rhEAo3CrZT0XG4VX4Rq48ibtQ4XOMcKz3cW+gQbjG43zEuH0gS9ww8yLIhyX7C8JDQj7KhdLcGt/x+22gUnUiDzVzxSgj9nv72xnSkKJYKSPc8fT+SgaaEjFOPROjn2VOrZie8SWu9hKBDhsKF4qSNWgN661HwqzjxIJwSpvxtVHhHoGRM="
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
